### ISSUE TITLE
Is there a way that single clicking the application icon will still open the application?

### ISSUE THREAD

**Issue by mal0121** [steventheworker/DockAltTab#11]
Love the application. My biggest problem is I'm very used to using one tap on icons to open them. It seems now that if you have the preview one tap will just close the preview and I have to tap again to open the window. If there is only one window on the application running it doesn't seem as necessary to select preview. 

Another problem I have found is that with modify click behaviour toggled one tap opens the window for a second but then closes again, unsure why it is doing that.  I think this is a one tap setting issue as there is no problem with a click.

Apologies if this has already been discussed / mentioned!

**Comment by sdburrows** [comment]
I think what you are describing is what I am reporting under Issues #8. I agree this is a wonder app in terms of productivity but the behaviour for click to toggle hiding and showing can sometimes be unpredictable.

**Comment by ssuess** [comment]
Same issue here, just switched from HyperDock. Mostly loving it, but would love the same behaviour I had before where a simple tap on the icon in the dock would activate the app. For now I have to click on the app icon in the dock, or hover to the window (even if there is only one) and tap there.

**Comment by steventheworker** [comment]
Will have an update for this within the week.

**Comment by Wurufururun** [comment]
Hi, any update on this?
And as an extra question - is there anything that can be done about the ~0.333s delay when clicking on an app to minimize it mentioned [here](https://github.com/steventheworker/DockAltTab/issues/8#issuecomment-1336092756), or is that some inherit limitation?

Other than that, thanks for all the work!

**Comment by steventheworker** [comment]
Sorry, we'll try again for within this week. 😅

**Comment by steventheworker** [comment]
@githubuser88442 v2.7 removed the 0.333s delay to hide the app, there is still one more delay that happens when you click dock icons while AltTab previews are showing, but that one is 0.167sec so it's less noticeable.

Really hoping to get this and issue #8 fixed in v2.8. It's inconsistent, but v2.7 made some progress on the issue w/ single taps, but it's inconsistent and seems to stop working based on how slow the tap or the app is...

**Comment by Moolynx** [comment]
@steventheworker, I don't know if its me or the app. But click to minimise stopped working in the latest release. I have tried restarting my laptop but it is still broken.

**Comment by steventheworker** [comment]
@Moolynx the yellow button on the previews? That should still work. No idea why it would persist between restarts...

You can try redownloading and replacing the .app. If that doesn't work still, try it with an older version before swapping back to the latest.

**Comment by briandpetersonOG** [comment]
@Moolynx same here on a M1 Mac Book Pro. I reverted to 2.5.

**Comment by Moolynx** [comment]
> @Moolynx the yellow button on the previews? That should still work. No idea why it would persist between restarts... Was it working before?
> 
> You can try redownloading and replacing the .app. If that doesn't work still, try it with an older version before swapping back to the latest.

@steventheworker I don't mean the yellow button but the app icon on the dock. In the previous version, I was able to minimise an app by clicking on the dock icon but it doesn't work anymore since this release. Seems @briandpetersonOG also has this problem too.

**Comment by briandpetersonOG** [comment]
Yes that's the functionality I lost. For example I have Google Calendar as a PWA on my dock. I might be working in another app. Instead of issuing a key command to "alt tab" I click the calendar open (from the dock). Then when I see I am not missing a meeting, I re-click the calendar icon, and it goes away leaving where I left off. This is one of the biggest misses on Apple's Dock vs Windows in my opinion.

**Comment by steventheworker** [comment]
@Moolynx, @briandpetersonOG I just reinstalled it on a virtual machine and it is working.

Pretty sure it's Input Monitoring permissions that are being ignored. Also the recent version asks for Screen Recording, maybe having that permission unchecked prevents the app from recognizing the other permissions.

1. Update to v2.7 again
1. Try re-checking "Input Monitoring" in Settings, restart DockAltTab
1. If it still doesn't work, try checking the Screen Recording permission, restart DockAltTab
1. If it still doesn't work, quit the app and run ```tccutil reset All com.steventheworker.DockAltTab```
1. Quit the Settings app, run DockAltTab and re-add the permissions

**Comment by Moolynx** [comment]
@steventheworker The permission for Input Monitoring for DockAltTab was already set to allow. I actually removed it from the list and it worked again. I don't know why. DockAltTab didn't ask for permission again too.

**Comment by ssuess** [comment]
It is hard to tell from the conversation above, is single clicking on the app icon now supposed to activate the app or not?

**Comment by briandpetersonOG** [comment]
@steventheworker One of those things worked! Thank you!

**Comment by briandpetersonOG** [comment]
@ssuess Yes it does work

**Comment by steventheworker** [comment]
Completely fixed in v2.91.0!
